name: Flask Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t flask-docker-app ./app

      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Test the app
        run: |
          sleep 10
          curl -s http://localhost:5001 | grep "Hola"