name: Flask Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t flask-docker-app .

      - name: Run Docker container in background
        run: |
          docker run -d -p 5001:5001 --name flask_test flask-docker-app
          sleep 5

      - name: Test the running app
        run: |
          curl http://localhost:5001 | grep "Hola desde Flask"